# Docker Network Configuration for MCP SSE Services
version: "1.0"

networks:
  litellm-net:
    external: true
    description: "Main network for LiteLLM and MCP service communication"
    
  postgres-net:
    external: true
    description: "PostgreSQL database network for secure database access"

# Network topology:
# - All MCP services connect to litellm-net for web communication
# - PostgreSQL service additionally connects to postgres-net for database access
# - Services bind to 127.0.0.1 only (no external exposure)
# - Communication within Docker networks using container names