version: '3.8'

services:
  # Admin-only MCP proxy with filesystem access
  mcp-proxy-admin:
    image: mcp-proxy-custom:latest
    container_name: mcp-proxy-admin
    restart: unless-stopped
    networks:
      - admin-mcp-net
    # NO PORT EXPOSURE - only accessible within Docker network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/administrator:/home/administrator:rw
      - /home/administrator/projects:/home/administrator/projects:ro
      - /home/administrator/secrets:/home/administrator/secrets:ro
      - ./servers-admin.json:/app/servers.json:ro
    command: ["--host", "0.0.0.0", "--port", "8080", "--named-server-config", "/app/servers.json"]

  # Developer MCP proxy without filesystem
  mcp-proxy-dev:
    image: mcp-proxy-custom:latest
    container_name: mcp-proxy-dev
    restart: unless-stopped
    networks:
      - dev-mcp-net
    # NO PORT EXPOSURE - only accessible within Docker network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/administrator/projects:/home/administrator/projects:ro
      - /home/administrator/secrets:/home/administrator/secrets:ro
      - ./servers-dev.json:/app/servers.json:ro
    command: ["--host", "0.0.0.0", "--port", "8080", "--named-server-config", "/app/servers.json"]

networks:
  admin-mcp-net:
    driver: bridge
  dev-mcp-net:
    driver: bridge