version: '3.8'

services:
  mcp-postgres-v2:
    build: .
    container_name: mcp-postgres-v2
    command: ["python", "-m", "services.mcp_postgres", "--mode", "sse", "--port", "8011"]
    environment:
      - DATABASE_URL=postgresql://admin:Pass123qp@postgres:5432/postgres
      - MCP_SSE_PORT=8011
      - PYTHONUNBUFFERED=1
    networks:
      - litellm-net
      - postgres-net
    restart: unless-stopped
    labels:
      - "service=mcp"
      - "type=postgres"
      - "version=v2"

  mcp-fetch-v2:
    build: .
    container_name: mcp-fetch-v2
    command: ["python", "-m", "services.mcp_fetch", "--mode", "sse", "--port", "8012"]
    environment:
      - MCP_SSE_PORT=8012
      - PYTHONUNBUFFERED=1
    networks:
      - litellm-net
    restart: unless-stopped
    labels:
      - "service=mcp"
      - "type=fetch"
      - "version=v2"

networks:
  litellm-net:
    external: true
  postgres-net:
    external: true