apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: mcp-code-executor
  description: MCP server for executing code with access to all MCP tools
spec:
  type: service
  lifecycle: production
  owner: administrators
