version: "3.8"

services:
  mcp-proxy:
    image: ghcr.io/tbxark/mcp-proxy:latest
    container_name: mcp-proxy
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./config.json:/config/config.json:ro
      - ./wrappers:/wrappers:ro
      - /home/administrator/projects:/workspace:ro
    networks:
      - mcp-net
      - postgres-net
      - minio-net
      - n8n-net
      - arangodb-net
    command: ["-config", "/config/config.json"]
    healthcheck:
      test: ["CMD", "/bin/sh", "-c", "test -f /config/config.json"]
      interval: 30s
      timeout: 5s
      retries: 3

networks:
  mcp-net:
    external: true
  postgres-net:
    external: true
  minio-net:
    external: true
  n8n-net:
    external: true
  arangodb-net:
    external: true
