version: "3.8"

services:
  mcp-proxy:
    image: ghcr.io/tbxark/mcp-proxy:latest
    container_name: mcp-proxy
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./config.json:/config.json
      - /home/administrator/projects:/workspace:ro
    networks:
      - mcp-net
    command: ["-config", "/config.json"]
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:9090/health"]
      interval: 30s
      timeout: 5s
      retries: 3

networks:
  mcp-net:
    external: true
