version: '3.8'

networks:
  mcp-internal:
    driver: bridge
    name: mcp-internal
  traefik-proxy:
    external: true
  postgres-net:
    external: true
  # Loki network - create if doesn't exist
  loki-net:
    name: loki-net
    driver: bridge
    external: false

x-common-settings: &common
  restart: unless-stopped
  networks:
    - mcp-internal
    - traefik-proxy
  logging:
    driver: "json-file"
    options:
      max-size: "10m"
      max-file: "3"
      labels: "com.docker.compose.service,com.docker.compose.project"

services:
  # For Phase 1, we'll continue using the existing proxy
  # but prepare for individual container architecture
  
  # MCP Proxy (transitional - will be replaced)
  mcp-proxy:
    <<: *common
    build:
      context: ./proxy
      dockerfile: Dockerfile
    container_name: mcp-proxy-composed
    ports:
      - "8586:8080"  # New port to avoid conflict with existing
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /workspace:/workspace
      - /home/administrator/projects:/home/administrator/projects:ro
      - ./proxy/servers-minimal.json:/app/servers.json:ro
    environment:
      - LOKI_URL=http://loki:3100
      - NETDATA_URL=http://netdata:19999
    command:
      - "--host"
      - "0.0.0.0"
      - "--port"
      - "8080"
      - "--named-server-config"
      - "/app/servers.json"
    networks:
      - mcp-internal
      - traefik-proxy
      - loki-net
    labels:
      - "com.docker.compose.service=mcp-proxy"
      - "com.mcp.type=proxy"
      - "com.mcp.version=transitional"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/servers/filesystem/sse"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # MCP Monitoring Service (Phase 1 - standalone)
  mcp-monitoring-standalone:
    <<: *common
    build:
      context: ./compose/monitoring
      dockerfile: Dockerfile
    container_name: mcp-monitoring-standalone
    networks:
      - mcp-internal
      - loki-net
      - traefik-proxy
    environment:
      - LOKI_URL=http://loki:3100
      - NETDATA_URL=http://netdata:19999
      - MCP_TRANSPORT=stdio
    labels:
      - "com.docker.compose.service=mcp-monitoring"
      - "com.mcp.type=monitoring"
      - "com.mcp.tools=5"
      - "com.mcp.status=phase1"
    # This will run in stdio mode for now
    # We'll add SSE wrapper in Phase 2

  # MCP Filesystem Service (Phase 1 - preparation)
  # Commented out until we resolve the wrapper
  # mcp-filesystem-standalone:
  #   <<: *common
  #   build:
  #     context: ./compose/filesystem
  #     dockerfile: Dockerfile
  #   container_name: mcp-filesystem-standalone
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #     - /workspace:/workspace:ro
  #     - /home/administrator/projects:/projects:ro
  #   labels:
  #     - "com.docker.compose.service=mcp-filesystem"
  #     - "com.mcp.type=filesystem"
  #     - "com.mcp.tools=11"
  #     - "com.mcp.status=phase1"

# Volumes for future use
volumes:
  mcp-data:
    name: mcp-data