version: '3.8'

networks:
  mcp-pilot:
    driver: bridge
    ipam:
      config:
        - subnet: 10.99.0.0/24
  postgres-net:
    external: true
  observability-net:
    external: true

services:
  mcp-postgresql:
    build:
      context: ./postgresql
      dockerfile: Dockerfile.http
    container_name: mcp-postgresql
    networks: [mcp-pilot, postgres-net]
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=Pass123qp
    ports:
      - "8080:8080"  # HTTP API endpoint for LiteLLM Smart Router
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      retries: 3
    restart: unless-stopped

  mcp-filesystem:
    build: ./filesystem
    container_name: mcp-filesystem
    networks: [mcp-pilot]
    volumes:
      - /home/administrator/projects:/workspace:ro
      - /tmp:/tmp:rw
    environment:
      - ALLOWED_PATHS=/workspace,/tmp
    ports:
      - "8081:8080"  # HTTP API endpoint for LiteLLM Smart Router
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      retries: 3
    restart: unless-stopped

  mcp-monitoring:
    build: ./monitoring
    container_name: mcp-monitoring
    networks: [mcp-pilot, observability-net]
    environment:
      - LOKI_URL=http://loki:3100
      - NETDATA_URL=http://netdata:19999
    ports:
      - "8082:8080"  # HTTP API endpoint for LiteLLM Smart Router
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      retries: 3
    restart: unless-stopped